openapi: "3.0.2"
info:
  title: Task Planner Application API
  version: "1.0"
servers:
  - url: http://localhost:5000
paths:
  /tasks:
    get:
      summary: "Get all tasks"
      responses:
        "200":
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["success", "failed"]
                  data:
                    $ref: "#/components/schemas/task"
        "400":
          description: Bad Request
    post:
      summary: "Add new task"
      requestBody:
        description: Request body for adding a new task"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task"
      responses:
        "200":
          description: Successfully added new task
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["success", "failed"]
        "400":
          description: Bad Request
  /tasks/{id}:
    delete:
      summary: "Delete task with ID"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the task to be deleted

      responses:
        "200":
          description: Successfully deleted task
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: ["success", "failed"]
        "400":
          description: Bad Request
        "401":
          description: Task does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  schemas:
    task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dueDate:
          type: string
          format: date
        reminderText:
          type: string
        reminderDescription:
          type: string
    error:
      type: object
      properties:
        status:
          type: string
        error:
          type: string
